version: "3"
services:
    mysql:
        image: "aladdinding/mysql:5.7.35"
        ports: 
        - "3306:3306"
        volumes: 
        - /data/atlassian-mysql:/var/lib/mysql
        environment: 
        - MYSQL_ROOT_PASSWORD=atlassian
        - TZ="Asia/Shanghai"
        restart: always
    confluence:
        image: "aladdinding/confluence:7.9.3"
        ports: 
        - "8601:8090"
        volumes: 
        - /data/confluence:/var/atlassian/confluence
        environment: 
        - TZ="Asia/Shanghai"
        links:
        - mysql
        restart: always
    jira:
        image: "aladdinding/jira:8.17.1"
        ports: 
        - "8600:8080"
        volumes: 
        - /data/jira:/var/atlassian/jira
        environment: 
        - TZ="Asia/Shanghai"
        links:
        - mysql
        restart: always

